### ISSUE TITLE
Fail to run sbt on the example-scala repo

### ISSUE THREAD

**Issue by pnerg** [codecov/example-scala#2]
Did a fresh clone of the example repo but I can't even start sbt.

```
/example-scala$ sbt
Loading /usr/share/sbt/bin/sbt-launch-lib.bash
[info] Loading global plugins from /home/xxx/.sbt/0.13/plugins
[info] Loading project definition from /git/github/example-scala/project
/git/github/example-scala/build.sbt:14: error: not found: value ScoverageSbtPlugin
ScoverageSbtPlugin.ScoverageKeys.coverageHighlighting := {
^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

After some fiddling I got it running with my project: 
https://github.com/pnerg/java-scala-util-converter 

I'll create a pull request later with suggestions to make this example project fly.

**Comment by stevepeak** [comment]
Thank you @pnerg I'm not sure why the build is failing, so any insight you can provide is great!

**Comment by pnerg** [comment]
No sweat, got it running for my project . So I'll use that as a base to
make a PR. Sometimes versions of plugins, SBT itself and Scala are just not
compatible.

**Comment by pnerg** [comment]
PR is merged, closing issue
