### ISSUE TITLE
README and .travis.yml conflict

### ISSUE THREAD

**Issue by bdarfler** [codecov/example-scala#4]
I'm very confused. The `.travis.yml` uses curl bash where as the README recommends the python approach but in a different why then is seen in the Scala section of https://codecov.io/guide. What is the right approach?

**Comment by stevepeak** [comment]
Sorry for the confusion, we are cleaning up our documentation very soon! They both work but we suggest the bash upload:

```
after_success:
  bash <(curl -s https://codecov.io/bash)
```

**Comment by bdarfler** [comment]
@stevepeak thanks! I have it running but I'm not seeing coverage show up

https://gist.github.com/bdarfler/02c5d6bf478d9f942fea
